### ISSUE TITLE
Using our local deployment of Llama 3 70B parameters

### ISSUE THREAD

**Issue by nyck33** [zorazrw/agent-workflow-memory#2]
Where can I switch out OpenAI api endpoints with our local Llama3?

**Comment by zorazrw** [comment]
Hi! Currently our code only supports API-based gpt models. But it should be pretty easy to use other models, by adjusting the model calling code in induction (for [webarena](https://github.com/zorazrw/agent-workflow-memory/blob/a744709d765ab8bc64bb63d6a032de9167f9950e/webarena/induce_prompt.py#L86) and [mind2web](https://github.com/zorazrw/agent-workflow-memory/blob/a744709d765ab8bc64bb63d6a032de9167f9950e/mind2web/online_induction.py#L53)) and generation ([webarena](https://github.com/zorazrw/agent-workflow-memory/blob/a744709d765ab8bc64bb63d6a032de9167f9950e/webarena/agents/basic/agent.py#L60) and [mind2web](https://github.com/zorazrw/agent-workflow-memory/blob/main/mind2web/utils/llm.py)) procedures.
