### ISSUE TITLE
Token Limit Exceeded in Workflow Generation.

### ISSUE THREAD

**Issue by Xinyu-Pang** [zorazrw/agent-workflow-memory#3]
- ## Description
When running experiments (details below), I encounter errors when generating workflows using gpt-3.5-turbo caused by the **query token limits**.   

I wonder whether this is acceptable.  

- ### Error
![1727860097259](https://github.com/user-attachments/assets/ce9fc817-b4c1-4fb3-9089-665e9e7da5e1)

- ### Implementation Details
  - **model**: gpt-3.5-turbo
  - **benchmark**: test_domain
  - **website**: tripadvisor
  
  Upon generating workflows for approximately 9 examples, the prompt exceeds the token limit, resulting in the error shown above. As a consequence, subsequent examples rely on existing workflows, halting the generation of new workflows.

Thanks for your response!

**Comment by zorazrw** [comment]
Hi! This can happen when the model generates too many lengthy workflows, but this did not happen often during my experiments. One general advice is to keep the induced workflow short enough to fit into the context, e.g., keep temperature=0 or try sampling multiple times to get the shortest workflows. Alternatively, switching to longer-context models also works (I remember there was a 32k gpt-3.5 variant but it seems no longer available). 
At the very least, it is okay to not input all workflows for one example, and/or not induce workflows only after this example. It should not affect the final results too much.
Hope this helps!

**Comment by Xinyu-Pang** [comment]
Thanks a lot!
