### ISSUE TITLE
No such file or directory: 'data/scores_all_data.pkl'

### ISSUE THREAD

**Issue by donggehan** [zorazrw/agent-workflow-memory#7]
Hi, thanks for the interesting work!
I'm trying to run the offline_induction.py
```code python offline_induction.py --mode auto --domain Travel --subdomain Airlines --website aa --model "gpt-4o" --output_dir "workflow"```
within mind2web, and I'm encountering this error: (Line 97 of offline_induction.py)
No such file or directory: ```'data/scores_all_data.pkl'```
In the data folder, there are only test/, train/, and memory/. Could you please help advice where the ```scores_all_data.pkl``` come from? Thanks a lot!

**Comment by zorazrw** [comment]
This [link](https://buckeyemailosu-my.sharepoint.com/personal/deng_595_buckeyemail_osu_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fdeng%5F595%5Fbuckeyemail%5Fosu%5Fedu%2FDocuments%2FMind2Web%2Fscores%5Fall%5Fdata%2Epkl&parent=%2Fpersonal%2Fdeng%5F595%5Fbuckeyemail%5Fosu%5Fedu%2FDocuments%2FMind2Web&ga=1) seems to work. It's a bit hard to find in their repo, I'll add this link to my repo too for the ease of downloading.

**Comment by donggehan** [comment]
Thank you so much!

**Comment by xiaobaishu0097** [comment]
Hi @zorazrw, Would you mind uploading scores_all_data.pkl file again? It seems that the updated link failed again.

**Comment by AtsuMiyai** [comment]
I encounter the same issue as @xiaobaishu0097 
@zorazrw Could you please upload scores_all_data.pkl file again?

**Comment by AtsuMiyai** [comment]
This issue has the 'data/scores_all_data.pkl'.
https://github.com/OSU-NLP-Group/Mind2Web/issues/35
Is this the same one?

**Comment by Eyict** [comment]
> This issue has the 'data/scores_all_data.pkl'. [OSU-NLP-Group/Mind2Web#35](https://github.com/OSU-NLP-Group/Mind2Web/issues/35) Is this the same one?

Thank you so much!
